DELETE FROM import_metadata ;
--
DELETE FROM work_activity ;
DELETE FROM work_log ;
DELETE FROM issue_relationship ;
DELETE FROM issue_user ;
DELETE FROM issue_team ;
DELETE FROM issue_custom_field_value ;
DELETE FROM issue_attachment ;
DELETE FROM issue_watcher ;
DELETE FROM issue_team ;
DELETE FROM issue_user ;
DELETE FROM work_log ;
DELETE FROM issue_relationship ;
DELETE FROM issue WHERE parentIssueId IS NOT NULL ;
DELETE FROM issue ;
DELETE FROM issue_category ;
DELETE FROM project_team ;
DELETE FROM project_member ;
DELETE FROM project_tracker ;
DELETE FROM tracker_custom_field ;
DELETE FROM project_custom_field ;
DELETE FROM custom_field_value ;
DELETE FROM custom_field ;
DELETE FROM version ;
DELETE FROM project WHERE parentProjectId IS NOT NULL ;
DELETE FROM project ;
DELETE FROM tracker ;
DELETE FROM issue_priority ;
DELETE FROM issue_status ;
DELETE FROM user_team ;
DELETE FROM user ;
DELETE FROM team ;